apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searchable-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: HEAD
    path: k8s/overlays/prod/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: searchable-from-book
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
